---
title: "Poison_time_deo"
output: html_document
---

---
title: "Estimating COVID-19 excess mortality"
date: '`r format(Sys.Date(),"%e de %B, %Y")`'
author: Aurora Hofman, Giovanni Rigolino, Paul Rognon
output:
  pdf_document:
    number_sections: yes
    toc: yes
    includes:  
      in_header: my_header.tex
params:
  stanfile: "Neg_bin_time_dep.stan"
  iter: 5000
  adapt_delta: 0.99
  max_treedepth: 15
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
#Reading the data
data_netherland<- read.csv("/Users/aurorahofman/Documents/Utveksling/Baysiana/UPC-Final-Project-Bayesian-Analysis/Excess_death/data/Death_week_2_17_netherland.csv", sep = ";")

```


```{r, include=FALSE}
#Extracting the data for the Netherlands
mean_netherland <- as.vector(as.matrix(data_netherland)[,6])
netherland_2020<-as.vector(as.matrix(data_netherland)[,5])
```


```{r}
create_list <- function(N, E, O){
  data_list <-  list(
  N = N, 
  E = E,
  O = O,
  sigma_a = 0.01,
  sigma_b = 4,
  alpha_mu = 0,
  alpha_sigma = 4,
  beta_a = -1, 
  beta_b = 1
  )
  return(data_list)
}
```

```{r, include= FALSE}
data_list_netherland <- create_list(length(mean_netherland), mean_netherland, netherland_2020)

```

```{r}
risk_netherland <- stan("/Users/aurorahofman/Documents/Utveksling/Baysiana/UPC-Final-Project-Bayesian-Analysis/Excess_death/testing/Aurora_testing/test_poisson_simple.stan", iter = 1000, chains = 4,
  data = data_list_netherland, seed = 1, control = list( max_treedepth = params$max_treedepth))
```



```{r, include=FALSE}
####################
# Helper functions
####################

#Function for output graphs
plot_risk <- function(data, country_name){
  g<- ggplot(data = data, aes(x = week, y = theta)) + geom_point() + geom_line(lty = 2) +
    geom_line(aes(week, CI_lower), col = "blue", lty = 2) +
    geom_line(aes(week, CI_upper), col = "blue", lty = 2) + 
    geom_hline(yintercept = 1, col = "red")+
    ggtitle("Relative risk for" , country_name)
  ggsave(paste0("output_",country_name,".png"))
  return(g)
}

# Function for creating the dataframe with thetas and the bounds for the credible interval. 

create_CI_theta_vec <- function(risk_data, N){
  fit<-summary(risk_data)
  results <- as.data.frame(fit$summary)
  
  CI_upper <- exp(results$`97.5%`[1:N]) #+results$`97.5%`[(N+1):(2*N)])
  CI_lower <- exp(results$`2.5%`[1:N]) #+results$`2.5%`[(N+1):(2*N)])

  theta <- exp(results$mean[1:N]) #+results$mean[(N+1):(2*N)])
  week <- seq(1:N)
  data <- data.frame(week, CI_upper, CI_lower, theta)
  return(data)

}
```

### The Netherlands

<!-- not sure if we need this in the report -->
```{r, }
print(risk_netherland)
```

<!-- can this be used for validation?  -->

```{r}
data_netherland <- create_CI_theta_vec(risk_netherland, length(mean_netherland))
plot_risk(data_netherland, "Netherland")
```
