---
title: "Question on Final Project"
author: "Group 1  "
date: "5/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We are interested in modelling the excess death due to COVID-19

We are modeelling:

$$(2)\hspace{0.3cm}O_i \sim Poisson(E_i\theta_i)$$

where $E_i$ is the expected number of deaths in week $i$ that we estimate as the historical average of death for week $i$ in yours prior to 2020 and $\theta_i$ the risk in week $i$. In a way it is a decomposition of $\lambda_i$ between its known expected value $E_i$ and a perturbation $\theta_i$. $\theta_{i,2020}$ larger than 1 would mean excess death, we can build a credible interval for $\theta_{i,2020}$ to see if it includes 1. Then we can build on a hierarchical model adding countries and explanatory variables for the risk $\theta_i$ (% of elderly people, time after lockdown). Doing it in similar way it is done in spatial epidemiology, if I remember well, for example:

$log(\theta_i) \sim Normal(\beta_o + \beta_1 X_1 + \beta_2 X_2,\sigma^2)$

Also we can think of modelling the dependence between weeks $i$ as spatial epidemiology models dependence between contiguous spatial units.


