---
title: "Divergency"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://mc-stan.org/users/documentation/case-studies/divergences_and_bias.html

Using this link in an atempt to explore convergence. Without succes... 

```{r}
params_belgium <- as.data.frame(rstan::extract(risk_belgium, permuted=FALSE))
names(params_belgium) <- gsub("chain:1.", "", names(params_belgium), fixed = TRUE)
names(params_belgium) <- gsub("[", ".", names(params_belgium), fixed = TRUE)
names(params_belgium) <- gsub("]", "", names(params_belgium), fixed = TRUE)
params_belgium$iter <- 1:2000

par(mar = c(4, 4, 0.5, 0.5))
plot(params_belgium$iter, log(params_belgium$sigma), col="red", pch=16, cex=0.8,
     xlab="Iteration", ylab="log(sigma)", ylim=c(-6, 4))
```

```{r}
divergent <- get_sampler_params(risk_belgium, inc_warmup=FALSE)[[1]][,'divergent__']
sum(divergent)/2000
```
```{r}
divergent <- get_sampler_params(risk_belgium, inc_warmup=FALSE)[[1]][,'divergent__']
params_belgium$divergent <- divergent

div_params_belgium <- params_belgium[params_belgium$divergent == 1,]
nondiv_params_belgium <- params_belgium[params_belgium$divergent == 0,]

par(mar = c(4, 4, 0.5, 0.5))
plot(nondiv_params_belgium$log_theta_time.16, (nondiv_params_belgium$sigma),
     xlab="log_theta_1", ylab="log(sigma)", xlim=c(0, 1), ylim=c(0,0.5),
     col="red", pch=16, cex=0.8)
points(div_params_belgium$log_theta_time.16, (div_params_belgium$sigma),
       col="green", pch=16, cex=0.8)
```

################################
# USING A REPARAMETRIZATION OF THE MODEL (ckeck that tis is true§!! )
```{r}
risk_belgium <- stan(file= "poison_time_dep.stan", iter = 5000, warmup = 2000, chains = 4,
  data = data_list_belgium, seed = 1, control = list(adapt_delta = 0.99, max_treedepth = params$max_treedepth))
```
We can see that the divergencies are clustered in the "bottelneck






```{r}
risk_belgium
```


###################################### MCMC diagnostics##################################
```{r}
available_mcmc(pattern = "_nuts_")
```

```{r}
lp_belgium <- log_posterior(risk_belgium)
head(lp_belgium)
```
```{r}
np_belgium <- nuts_params(risk_belgium)
np_belgium<-np_belgium[,-(39)]
head(np_belgium)
```

```{r}
posterior_belgium <- as.array(risk_belgium)
posterior_belgium <- posterior_belgium[, -("")]
```

```{r}
color_scheme_set("darkgray")
mcmc_parcoord(posterior_belgium, np = np_belgium)
```

```{r}
mcmc_pairs(posterior_belgium, np = np_belgium, pars = c("sigma","sigma_time","log_theta[1]", "log_theta_time[1]"), 
           off_diag_args = list(size = 0.75))
```
```{r}
# assign to an object so we can reuse later
scatter_sigma_belgium <- mcmc_scatter(
  posterior_belgium, 
  pars = c("log_theta[1]", "sigma"), 
  transform = list(sigma = "log"), # can abbrev. 'transformations'
  np = np_belgium, 
  size = 1
)
scatter_sigma_belgium
```
```{r}
# assign to an object so we can reuse later
scatter_sigma_time_belgium <- mcmc_scatter(
  posterior_belgium, 
  pars = c("log_theta_time[1]", "sigma_time"), 
  transform = list(sigma_time = "log"), # can abbrev. 'transformations'
  np = np_belgium, 
  size = 1
)
scatter_sigma_time_belgium
```


########################################################



```{r}
params_belgium <- as.data.frame(rstan::extract(risk_belgium, permuted=FALSE))
names(params_belgium) <- gsub("chain:1.", "", names(params_belgium), fixed = TRUE)
names(params_belgium) <- gsub("[", ".", names(params_belgium), fixed = TRUE)
names(params_belgium) <- gsub("]", "", names(params_belgium), fixed = TRUE)
params_belgium$iter <- 1:3000

par(mar = c(4, 4, 0.5, 0.5))
plot(params_belgium$iter, log(params_belgium$sigma), col="red", pch=16, cex=0.8,
     xlab="Iteration", ylab="log(sigma)", ylim=c(-6, 4))
```
```{r}
running_means <- sapply(params_belgium$iter, function(n) mean(log(params_belgium$sigma)[1:n]))

par(mar = c(4, 4, 0.5, 0.5))
plot(params_belgium$iter, running_means, col="red", pch=16, cex=0.8, ylim=c(-4, -2),
    xlab="Iteration", ylab="MCMC mean of log(sigma)")

running_means_2 <- sapply(params_belgium$iter, function(n) mean(log(params_belgium$sigma_time)[1:n]))

par(mar = c(4, 4, 0.5, 0.5))
plot(params_belgium$iter, running_means_2, col="red", pch=16, cex=0.8, ylim=c(-1, -2),
    xlab="Iteration", ylab="MCMC mean of log(sigma)")

```

```{r}
divergent <- get_sampler_params(risk_belgium, inc_warmup=FALSE)[[1]][,'divergent__']
sum(divergent)/2500
params_belgium$divergent <- divergent

div_params_belgium <- params_belgium[params_belgium$divergent == 1,]
nondiv_params_belgium <- params_belgium[params_belgium$divergent == 0,]

par(mar = c(4, 4, 0.5, 0.5))
plot(nondiv_params_belgium$log_theta.1, (nondiv_params_belgium$sigma_time),
     xlab="log_theta_1", ylab="log(sigma_time)", xlim=c(-0.5, 0.5), ylim=c(0,0.5),
     col="red", pch=16, cex=0.8)
points(div_params_belgium$log_theta.1, (div_params_belgium$sigma_time),
       col="green", pch=16, cex=0.8)

par(mar = c(4, 4, 0.5, 0.5))
plot(nondiv_params_belgium$log_theta.1, (nondiv_params_belgium$sigma),
     xlab="log_theta_1", ylab="log(sigma)", xlim=c(-0.5, 0.5), ylim=c(0,0.5),
     col="red", pch=16, cex=0.8)
points(div_params_belgium$log_theta.1, (div_params_belgium$sigma),
       col="green", pch=16, cex=0.8)
```



######################################

```{r, include=FALSE}
####################
# Helper functions
####################

#Function for output graphs
plot_risk <- function(data, country_name){
  g<- ggplot(data = data, aes(x = week, y = theta)) + geom_point() + geom_line(lty = 2) +
    geom_line(aes(week, CI_lower), col = "blue", lty = 2) +
    geom_line(aes(week, CI_upper), col = "blue", lty = 2) + 
    geom_hline(yintercept = 1, col = "red")+
    ggtitle("Relative risk for" , country_name)
  ggsave(paste0("output_",country_name,".png"))
  return(g)
}

# Function for creating the dataframe with thetas and the bounds for the credible interval. 

create_CI_theta_vec <- function(risk_data, N){
  fit<-summary(risk_data)
  results <- as.data.frame(fit$summary)
  
  CI_upper <- exp(results$`97.5%`[1:N] +results$`97.5%`[(N+1):(2*N)])
  CI_lower <- exp(results$`2.5%`[1:N] +results$`2.5%`[(N+1):(2*N)])

  theta <- exp(results$mean[1:N] +results$mean[(N+1):(2*N)])
  week <- seq(1:N)
  data <- data.frame(week, CI_upper, CI_lower, theta)
  return(data)

}
```

### The Netherlands

```{r}
library(bayesplot)
posterior <- as.data.frame(risk_netherland)
mcmc_trace(risk_belgium, pars = "log_theta_time[3]")
mcmc_trace(risk_belgium, pars = "log_theta_time[4]")
mcmc_trace(risk_belgium, pars = "log_theta_time[6]") 
mcmc_trace(risk_belgium, pars = "sigma") 

```
