---
title: "Excess_death_week_2_17_negbin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Excess_death_netherland_week_2-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
average_death_per_year = (139223 + 147134+ 148997 + 150214 + 153363 + 151793)/6
average_per_week = average_death_per_year/52
average_per_week
```

```{r}
alpha <- 8.1503
beta <- 0.0028544

p = beta/(1+beta)


gamma_vec <- dgamma(theta, shape= alpha, scale = 1/beta)
```


a/(a+b) = 1/(1+0.00285) , a*b/((a+b)^2*(a+b+1)) = 0.05^2

because r = alpha and p beta= p/(1-p)
```{r}
a = 0.13315
b = 0.000379478

mu = alpha
sigma = 4
```


```{r}
data<- read.csv("Death_week_2_17_netherland.csv", sep = ";")
```

```{r}
(period_1<-as.vector(as.matrix(data)[1:4,2:4]))
(period_2<-as.vector(as.matrix(data)[5:8,2:4]))
(period_3<-as.vector(as.matrix(data)[9:12,2:4]))
(period_4<-as.vector(as.matrix(data)[13:16,2:4]))
```

```{r}
N <- length(period_1)
data_list <- list(
  N = N, 
  y1 = period_1,
  y2 = period_2,
  y3 = period_3,
  y4 = period_4,
  a = 0.0003794,
  b = 0.13315,
  mu = mu, 
  sigma = sigma
  )

```

```{r}
death_netherland <- stan("exp_death_week_2_17_neg_bin.stan", iter = 1000, chains = 4,
  data = data_list, seed = 1)

```
```{r}
print(death_netherland)
```


```{r}
params <- (paste0("p", 1:4 ,""))
plot_title <- ggtitle("Posterior distributions of lambda, heterogeneous model", "with medians and 80% intervals")
p_heter <- mcmc_areas(posterior, 
  pars = c(params), 
  prob = 0.8) + plot_title
p_heter

params <- (paste0("r", 1:4 ,""))
plot_title <- ggtitle("Posterior distributions of lambda, heterogeneous model", "with medians and 80% intervals")
p_heter <- mcmc_areas(posterior, 
  pars = c(params), 
  prob = 0.8) + plot_title
p_heter
```

```{r}
traceplot(death_netherland)
```
```{r}
posterior <- as.data.frame(death_netherland)
```

```{r}
n_sim <- 1000
post_predict1 <- rnbinom(n_sim, size = posterior[, "r1"], prob=(1-posterior[, "p1"]))
post_predict2 <- rnbinom(n_sim, size = posterior[, "r2"], prob=(1-posterior[, "p2"]))
post_predict3 <- rnbinom(n_sim, size = posterior[, "r3"], prob=(1-posterior[, "p3"]))
post_predict4 <- rnbinom(n_sim, size = posterior[, "r4"], prob=(1-posterior[, "p4"]))
## credibility interval
CI1<- quantile(post_predict1, c(0.05, 0.95))
CI2<- quantile(post_predict2, c(0.05, 0.95))
CI3<- quantile(na.omit(post_predict3), c(0.05, 0.95))
CI4<- quantile(na.omit(post_predict4), c(0.05, 0.95))

mean1<-mean(post_predict1)
mean2<-mean(post_predict2)
mean3<-mean(na.omit(post_predict3))
mean4<-mean(na.omit(post_predict4))
```


```{r}
N<-4
point_est <- c(rep(mean1, N), rep(mean2,N), rep(mean3,N), rep(mean4,N))
CI_lower <- c(rep(CI1[1], N), rep(CI2[1], N), rep(CI3[1], N), rep(CI4[1], N))
CI_upper <- c(rep(CI1[2], N), rep(CI2[2], N), rep(CI3[2], N), rep(CI4[2], N))
```

```{r}
data_2020<-as.vector(as.matrix(data)[,5])

posterior_data <- tibble(point_est, CI_lower, CI_upper, week = seq(2,17), data2020 = data["X2020"] )
```

```{r}
ggplot(data = posterior_data, aes(week, data_2020)) + geom_point() + geom_line(lty = 2) +
  geom_line(aes(week, point_est), col = "red") + 
  geom_line(aes(week, CI_lower), col = "blue", lty = 2) +
  geom_line(aes(week, CI_upper), col = "blue", lty = 2)
```

